### ISSUE TITLE
Crash upon opening PGN file 

### ISSUE THREAD

**Issue by nbca** [daylen/stockfish-mac#65]
Hi 

I just downloaded stockfish and was trying to load a PGN file (attached). It crashed stockfish. I am able to open other files but this one crashed it.

My OS is Catalina 10.15.5 on MacBook Air 2020. I downloaded stockfish from the App Store today so I believe I have the latest build.

Thanks

[CB - Chess Openings BASIC.pgn.zip](https://github.com/daylen/stockfish-mac/files/5066658/CB.-.Chess.Openings.BASIC.pgn.zip)

**Comment by daylen** [comment]
This is now fixed at HEAD, but it may take some time for the fix to reach the App Store. Thanks for reporting!

**Comment by nbca** [comment]
Thanks, is there a way I can update the file on my Mac to get it to work?

Thanks
________________________________

**Comment by daylen** [comment]
I just submitted version 2.2.3 to Apple for review. It should be available soon!

The bug was that the app was trying to interpret the parentheses inside of comments. So if you have something like `{ my comment ( some text }` where there is no closing `)` then the app would crash. The app is now more resilient to this.

**Comment by nbca** [comment]
Thanks the update hit the App Store for laptops.

The same error seems to exist on the iPhone too. Can you please let me know if that bug is also fixed.

Thanks

________________________________

**Comment by daylen** [comment]
Unfortunately I don't develop the iPhone app. Have you tried an alternative app like https://itunes.apple.com/us/app/smallfish-chess-for-iphone/id675049147?mt=8?
